=== denysaleksandrov/tcsa-collectors/examples/kafka_avro_custom_collector/configuration/config_input_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "bootstrap_server",
    "num_workers",
    "topic_name",
    "group_id",
    "auto_offset_reset",
    "num_threads"
  ],
  "properties": {
    "bootstrap_server": {
      "description": "The Source Kafka Server from where the data is collected",
      "type": "string",
      "title": "Bootstrap Server"
    },
    "schema_registry_url": {
      "description": "Schema Registry URL",
      "type": "string",
      "title": "Schema Registry URL"
    },
    "basic_auth_username": {
      "description": "Basic Auth Username",
      "type": "string",
      "title": "Basic Auth Username"
    },
    "basic_auth_password": {
      "description": "Basic Auth Password",
      "type": "string",
      "title": "Basic Auth Password"
    },
    "num_workers": {
      "description": "The number of workers for consumer should be equal to number of partition in source kafka topic",
      "type": "integer",
      "title": "Number of Worker Process",
      "minimum": 1,
      "maximum": 8,
      "default": 4
    },
    "topic_name": {
      "description": "Source Kafka Topic ",
      "type": "string",
      "title": "Topic Name"
    },
    "group_id": {
      "description": "Group Id for the kafka consumer",
      "type": "string",
      "title": "Group Id",
      "default": "custom-kafka-consumer-group"
    },
    "auto_offset_reset": {
      "description": "behavior of the consumer when there is no committed position",
      "type": "string",
      "title": "Auto Offset Reset",
      "default": "earliest",
      "enum" :["earliest", "latest", "none"]
    },
    "num_threads": {
      "description": "The Number of threads",
      "type": "integer",
      "title": "Number of Threads",
      "minimum": 1,
      "maximum": 16,
      "default": 4
    },
    "sink": {
      "description": "This is the destination kafka details",
      "type": "object",
      "title": "Destination Kafka",
      "properties": {
        "topic": {
          "description": "The topic to publish output Data",
          "type": "string",
          "title": "Topic Name",
          "default": "vsa_metrics_raw"
        },
        "properties": {
          "description": "Destination kafka details",
          "type": "object",
          "title": "Properties",
          "properties": {
            "bootstrap_servers": {
              "description": "Destination kafka Server address",
              "type": "string",
              "title": "Destination kafka address",
              "default": "internal-kafka-bootstrap:9092"
            }
          },
          "required": [
            "bootstrap_servers"
          ]
        }
      },
      "required": [
        "topic",
        "properties"
      ]
    }
  }
}

=== denysaleksandrov/tcsa-collectors/config.json
{
  "bootstrap_server": "localhost:9092",
  "num_workers": 1,
  "topic_name": "topic-mnrdata",
  "group_id": "sample_group",
  "auto_offset_reset": "latest",
  "num_threads": 4,
  "sink": {
    "topic": "output-events",
    "properties": {
      "bootstrap_servers": "edge-kafka-bootstrap:9093"
    }
  }
}

=== denysaleksandrov/tcsa-collectors/examples/kafka_avro_custom_collector/configuration/config.json
{
  "bootstrap_server": "http://127.0.0.1:9092",
  "schema_registry_url": "http://127.0.0.1:8081",
  "basic_auth_username": "user_name",
  "basic_auth_password": "password",
  "num_workers": 1,
  "topic_name": "metrics",
  "group_id": "sample_group",
  "auto_offset_reset": "latest",
  "num_threads": 4,
  "sink": {
    "topic": "vsa_metrics_raw",
    "properties": {
      "bootstrap_servers": "edge-kafka-bootstrap:9093"
    }
  }
}

=== denysaleksandrov/tcsa-collectors/examples/topology_kafka_collector/configuration/config.json
{
  "bootstrap_server": "127.0.0.1:9092",
  "num_workers": 1,
  "topic_name": "topology_demo",
  "group_id": "topology-kafka-collector-group2",
  "auto_offset_reset": "latest",
  "num_threads": 4,
  "sink": {
    "topic": "inv_topo",
    "properties": {
      "bootstrap_servers": "internal-kafka-bootstrap:9092"
    }
  }
}
