=== denysaleksandrov/tcsa-collectors/examples/k8s_custom_events_collector/configuration/config_input_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "host": {
      "type": "string",
      "title": "Host Name",
      "description": "Host Name Required"
    },
    "verify_ssl": {
      "type": "boolean",
      "title": "verify SSL",
      "description": "SSL verification Required",
      "default": false
    },
    "cert_file": {
      "type": "string",
      "title": "Client Certificate File",
      "description": "Client Certificate File Required",
      "default": ""
    },
    "key_file": {
      "type": "string",
      "title": "Client Key File",
      "description": "Client Key File Required",
      "default": ""
    },
    "ssl_ca_cert": {
      "type": "string",
      "title": "SSL Certificate File",
      "description": "SSL Certificate File Required",
      "default": ""
    },
    "sink": {
      "description": "This is the destination kafka details",
      "type": "object",
      "title": "Destination Kafka",
      "properties": {
        "topic": {
          "description": "The topic to publish output Data",
          "type": "string",
          "title": "Topic Name",
          "default": "vsa_events_raw"
        },
        "properties": {
          "description": "Destination kafka details",
          "type": "object",
          "title": "Properties",
          "properties": {
            "bootstrap_servers": {
              "description": "Destination kafka Server address",
              "type": "string",
              "title": "Destination kafka address",
              "default": "edge-kafka-bootstrap:9093"
            }
          },
          "required": [
            "bootstrap_servers"
          ]
        }
      },
      "required": [
        "topic",
        "properties"
      ]
    }
  },
  "required": [
    "host",
    "verify_ssl",
    "cert_file",
    "key_file",
    "ssl_ca_cert"
  ]
}

=== denysaleksandrov/tcsa-collectors/examples/k8s_custom_metrics_collector/configuration/config.json
{
  "host": "https://10.198.97.29:6443",
  "verify_ssl": true,
  "cert_file": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lJUlEwVzZPV1RZL0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBMU1EZ3dNVFExTlRSYUZ3MHlOREExTURjd01UVXdOVFJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQThCWjZ0d0RSbDk0TkRPbXYKTkxBVUJXc3I4Z2ExSUxsZHE5TU40Uy9YTlNZM0xxakZmTUJzZW45a1ljdmNRMC83NlpsajdZTTBhSTJ6YnNoNwpWKzVwSTZObmxnNmIvLzNwdmV4RENBYnVnVGRmMHM0Q05aaEl2QkoyNWpUdEdIeldhUzhtVEpXcFkxcFNFSzIrCk9BZFlhS1RmZ1ZCcFBWM0tWOGFDMHlPUmtLYk14VWd5d2Ywb3YvaFhkRjFjSmMwUmFNcUpld2MxTUZMUURsdEYKVzlZazExbVhmZENvdWwvZDE3S2RaN0k2eFpJcWpOQlV1RnRBazE1c3Y3SCtndFZ1WkNSYjczd29uZTY1VC9XQgp3L3YrbDBoUjFkSS9ndmNhR3V4OEd0cHB1MFYyelh1T0ZWVXdnYjJadmRvK1pMcUhsS2xma1NFM0hEQ1kxelVsCnVGK1Rid0lEQVFBQm8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVUyMHNPNjk5WmxNeEk5MGVGTDVUSEwrb1hrdUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJaWMxSk9BUmtaUG1FUnkzbkxWeHNHVjJ1TEhHU2dzeitzM1VGNGhKVGRlVnhQQ2NmTGd0SkhBCmJkcHN3ajFucVRNUG1EVlBidjhOdTZFV0w2d2VPem9DNXExaWQ0WlBmUHIrNjFXVFRNczNVOEhRSDZoMHdmRDIKa2g3b0lua1ZxbXhWOXNQVkZmRHpuWmFLT05xNUlYTVMxays5bG9IajR3TGZhZ09PZG9SZTUvSVhoVlBaTWFaKwphWGZ2NmFuTHF3VC9rb2t4REgwY2pQYjlQeE82TEc2U0tvb0c4aFJWb1puaXRFN0FlcVEyd2tzSEJSdG5zZ0FGCjdaU1BHa2F2c3U1cFdyaVBlRnZTZjZOejFYRGRWL3B3Y29TOXdWaU13V0tDVVJzaHJDWVpnTGtVNUhWR2h6Q0YKRjRHNDVsdDhGSVc1a2NOS0tzQ05PeEZSa1c1WDY0az0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=",
  "key_file": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBOEJaNnR3RFJsOTRORE9tdk5MQVVCV3NyOGdhMUlMbGRxOU1ONFMvWE5TWTNMcWpGCmZNQnNlbjlrWWN2Y1EwLzc2WmxqN1lNMGFJMnpic2g3Vis1cEk2Tm5sZzZiLy8zcHZleERDQWJ1Z1RkZjBzNEMKTlpoSXZCSjI1alR0R0h6V2FTOG1USldwWTFwU0VLMitPQWRZYUtUZmdWQnBQVjNLVjhhQzB5T1JrS2JNeFVneQp3ZjBvdi9oWGRGMWNKYzBSYU1xSmV3YzFNRkxRRGx0Rlc5WWsxMW1YZmRDb3VsL2QxN0tkWjdJNnhaSXFqTkJVCnVGdEFrMTVzdjdIK2d0VnVaQ1JiNzN3b25lNjVUL1dCdy92K2wwaFIxZEkvZ3ZjYUd1eDhHdHBwdTBWMnpYdU8KRlZVd2diMlp2ZG8rWkxxSGxLbGZrU0UzSERDWTF6VWx1RitUYndJREFRQUJBb0lCQUh3VFVmWHpnVjNYenF6RwpzOW9weVI4SHhOMCtaQ3IyUVJlRWFoN2ZSM3ZiTlJkeTl5VENtUTB4ZXVJanBjQlB2S043dHkzTzZhM0MxV0ZDClVLUWZ2TXhETFV4YVhucU1jVmpLbWRXekoxMDJEZHAyeHFPR0FNalpUZ01vaFFOcnVLOEJRK3krUjV6bDE1VngKQk9ZVnZiWE94d2NnVkZMM2ZwT2dMb29KVHJnT3kydlMzS2tDY1BaUjNLNTZYaUYycEp2Y3p6dURoS1JOaHhIMwpyZnZSMG42UjJRMktwQzBZemxKbGNTR3gxc2ZmYWRnQjFNbW0yYVdSQU5WR0JkaWk4Ump0NHpvZ245VXEzSmpUCnZWOG1NRXFUTzFMbFpnbm9BRWlxYjVoUVdHcStDWlN2dkNVcm84MVEzMWFacUU0azhqMm1ncndSQ05ZbExUVUwKdXpMcEUvRUNnWUVBKzd3VHZ2U2RCV0NhUFZyR0l1bCt1ZGNSajhuMXR4TVFtc0tNWWtkbFBEb281ZDAwWUNzUApqMEY1Szl0RlljaWR5UzZFT0VNU2RPV3E4VUdQMHdTWlRXd1dwMEdvei9HUFc0SElnblVqd2pndnVuUXR6M0VBCm9lUEZyZ1FPRnNBWHA1VHNVeUhDRzFGd21tVlhHZ1hwQnJXeDFvakEwNjF1WVkwWENVVmhhUWtDZ1lFQTlDZmkKQWZ5ZmlDVU1HWEtHS013S2MyVmJ2WGhyUTZDeFZMaUVVb3loZWpmNmxjMHRpNlRQY0RpRDlZck00ZndrOWhCdwpkakpzbnUzSTlmSkpYQ2hUZ0hUM1N5V0o3RTdtQURYY2Q1aG9XODhucWUvSVhTM1lqUzJDVG9Lc2l1UVhmSlhuCnJuZ2hVN2lEL1FkK0RGK2dEMlBpdVVaRWZaZGtxenhhbjNiSERyY0NnWUJjbVBzK2M2WktzeFVwV25tbG4vUWcKa2c4QXNFNTFNRXNjVWxIbldOSFJUS2Q4bmxqRXd6SXZCT3Q0aVdqRkpsRjhEbU5PZXNXUVFHY1g1WUR0SXpUcworTVNBYzdPUUFoQTBuZEhPd3g0TE5EWENSVGdRcFVXUlIwS1ExeWNEa1ZkaUtuS2Z4YndyNWxJZ1NRUzRLdEpqCnlIUUpNVGFVNXFmQ3RHNXoxNVNVV1FLQmdGL0pFY3F6d0NhYVdpL1ZsVHFHS2dkeG1WY3cyZXdUSzk3UDhPR3QKMkYvcGZENnUyeEp3Mnd6c3J5Qnlqc1NOdGpadTVxQUlVa0xiaUw2c2lnbEVyTlcxalpzR3BDQjRKNVduaTlIRApraFdLcE1YdmsweXpBc1VJT0pueWZCeVZOWDJrRmR1RnQ1VnZ5eUJHZ3pYNWdnTG5yZmYvMERqeFh3WXF6R2JKCkkzanJBb0dBWlZZQXlmQmgyUXVjaHlVSDlnT2ZUVzdyb0ZJS0RvaWNaMFFDeHVDUitTTmlURUZMVnQvNWwyUXkKdkhMNTBMcjcyQ3hNcnd3WDRZa09JT0JjV0puNmpvZUVUWGtzNnFzRDJsTitLVUFoU2dnYXJ4OGtkNWNja1M5VwpiVFZBaUF4cmdvNUYxbldKWmFLdTlIVWhBbktlZmM4ZndhWDAyNjFEdVRUMWJUZ1duWTA9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==",
  "ssl_ca_cert":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXdPREF4TkRVMU5Gb1hEVE16TURVd05UQXhOVEExTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1YwCkppNTNJZU5GakVGbzdwMjlFSU0xUmN3TGhHUjZScUxyVDNZY005dHUzZlVYck5CZ3RsMVhZdnEzb1BtNGRqUWsKTDNWc3NwLzVreG9DK1BzYnBmUVVCN3FSZ0Q0ajlxTDFEUHZHeHU5azhyUExESytiZ2RLWjE3THl5OFZRQmIvRApCOEloUEdKK05kUGgyckovZWRzenhCUlgzZzI4UzlYbWdaUndWWjdvL1hSL25jbGxydWxhMlNpTHp4cFhSMzdqCkI1a3cwV1ljUzhaOVVPOFdzVjI2U1dCNXZNZXU3a2hRNWp1aE5xdnE5QUpRZFFkaXpPeEVxY05CT0YxaTFuK0kKdHdlZkNqdGhodE5lbGwrQUtoOG1rZVlFNzR2Qml1Z1FRdGc1UU1KNUQ0NHBXczdWemVxSjNLaGZzQXJOemVlYQpVUGRKTnNjUFRNMzZYTTVzVVNVQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGTnRMRHV2ZldaVE1TUGRIaFMrVXh5L3FGNUxnTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQUh6dytmb1dvT0JJcFU5TmR5MEJqOFpXTnRsT2xBSk9DSnY4Nk9MZmdMM2JsTQpGR2ovZUQ1emlKZFRpZ2hnN21Ta1NCdXBER0hiVWp5c1FWUTlsSDBINFpwUWs4QlY5N2N1a1BsZFQrUStYUkU1CnpzeDBIMkhBbkdGUHdvZFlhZSs1eFN3WWNDdFJPYUVWZ21KMXVQNkpBdGhYZVlMY2ZHZVh5akFlaTVrU1BIdE0KdllXNkZvYTcvSmdoemM2SDdSZnpYTEc1bUV3b1RjSXJRRmJQVldTUVFzVENNNlB2dkw0N1NqNDZOZzlWUmRPaAoyUEdqd3p5Nlh6Ly9CTXhpTkxvOFB6Z05HQ2pXb2JKYmRMU0Q3K01UZW9HSDhYaFROc2pTNDgwY01WaG5jTHlTCjhMYzNhNlR1eGx1Y2ZXZnQ2cHZ5Q3JoQTVEUzFkUFUrY3JkQUpvRG4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
}
